<!-- Message de notification -->
<?php if($flashBag->hasMessages() == true): ?>
    <aside id="notice" class="notice">
        <?php foreach($flashBag->fetchMessages() as $message): ?>
            <p><?= $message ?></p>
        <?php endforeach ?>
    </aside>
<?php endif; ?>

<h2 class="change-user-password-title"><i class="fa fa-pencil"></i>Modifier mon mot de passe</h2>

<form class="generic-form" action="<?= $requestUrl ?>/user/userDetail/changeUserpassword" method="POST">
    <ul>
        <li>
            <label for="oldPassword">Ancien mot de passe</label>
            <input type="password" name="oldPassword"/>
        </li>
            
        <li>    
            <label for="newPassword">Nouveau mot de passe</label>
            <input type="password" name="newPassword"/>
        </li>
        
        <li>    
            <label for="newPassword2">Confirmez le nouveau mot de passe</label>
            <input type="password" name="newPassword2"/>
        </li>
        
        <li>
            <input class="button" type="submit" value="Modifier"/>
        </li>
    </ul>
</form>