<h2 class="admin-title"><i class="fa fa-cogs"></i>Interface Admins</h2>

<section id="admin-links">
    
    <article class="admin-link">
        <a href="<?= $requestUrl ?>/admin/artists">
            <h3>Ajouter/Retirer des artistes dans le catalogue</h3>
        </a>
        <a href="<?= $requestUrl ?>/admin/artists">
            <img src="<?= $wwwUrl ?>/images/JazzCollage.jpg"></img>
        </a>
    </article>
    
    <article class="admin-link">
        <a href="<?= $requestUrl ?>/admin/records">
            <h3>Ajouter/Retirer des albums dans le catalogue</h3>
        </a>
        <a href="<?= $requestUrl ?>/admin/records">
            <img src="<?= $wwwUrl ?>/images/FusionCollage.jpg"></img>
        </a>
    </article>
    
    <article class="admin-link">
        <a href="<?= $requestUrl ?>/admin/genres">
            <h3>Ajouter/Retirer des genres dans le catalogue</h3>
        </a>
        <a href="<?= $requestUrl ?>/admin/genres">
            <img src="<?= $wwwUrl ?>/images/musicgenrescollage.png"></img>
        </a>
    </article>
    
</section>

<section id="admin-links" class="addOrDelete-tracks">
    
    <article class="admin-link">
        <a href="<?= $requestUrl ?>/admin/tracks">
            <h3>Ajouter/Retirer des morceaux aux albums du catalogue</h3>
        </a>
        <a href="<?= $requestUrl ?>/admin/tracks">
            <img src="<?= $wwwUrl ?>/images/TrackIllustration.png"></img>
        </a>
    </article>
    
</section>

<section id="admin-links" class="gestion-admins">
    
    <article class="admin-link">
        <a href="<?= $requestUrl ?>/admin/user">
            <h3>Gestion des administrateurs</h3>
        </a>
        <a href="<?= $requestUrl ?>/admin/user">
            <img src="<?= $wwwUrl ?>/images/admin.png"></img>
        </a>
    </article>
    
</section>