<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Projet Pro - GuigsCog'</title>
        
        <!-- Css Vendor -->
        <link rel="stylesheet" href="<?= $wwwUrl ?>/css/font-awesome.min.css"/>
        <link rel="stylesheet" href="<?= $wwwUrl ?>/css/normalize.css"/>
        <link href="https://fonts.googleapis.com/css?family=Risque&display=swap" rel="stylesheet">
    	<link href="https://fonts.googleapis.com/css?family=Titillium+Web&display=swap" rel="stylesheet">
    	<link href="https://fonts.googleapis.com/css?family=Bitter&display=swap" rel="stylesheet">
    
        <!-- Feuilles de styles de l'application -->
        <link rel="stylesheet" type="text/css" href="<?= $wwwUrl ?>/css/base.css"/>
        <link rel="stylesheet" href="<?= $wwwUrl ?>/css/form.css"/>
        <link rel="stylesheet" href="<?= $wwwUrl ?>/css/table.css"/>
        <link rel="stylesheet" href="<?= $wwwUrl ?>/css/button.css"/>
        <link rel="stylesheet" href="<?= $wwwUrl ?>/css/style.css"/>
    
        <!-- Librairie jQuery -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    
        <!-- JavaScript de l'application -->
        <script src="<?= $wwwUrl ?>/js/utilities.js"></script>
        <script src="<?= $wwwUrl ?>/js/classes/FormValidator.class.js"></script>
    </head>
    
    <body>
    
    <!-- En-tête commune -->
    <section id="login-section">
				<form id="site_search" action="<?= $requestUrl ?>/search" method="POST" aria-label="Search Guigscog">
                <input
                    id="search_q"
                    name="q"
                    type="text"
                    class="autocomplete"
                    value=""
                    autocapitalize="off"
                    autocorrect="off"
                    placeholder="Rechercher un artiste ou un album"
                    aria-label="Rechercher un artiste ou un album"/>
                <button
                    type="submit"
                    id="do_site_search"
                    class="submit button"
                    name=""
                    value=""
                    aria-label="Search">
                <i class="fa fa-search"></i>
                </button>
                <input type="hidden" class="advanced_search advanced_search_type" name="type" value="all"/>
            </form>
            <?php
                if($userSession->isAuthenticated()) {
                    ?>
                    
                    <div class="welcome">Bonjour <strong><a href="<?= $requestUrl ?>/user/userDetail"><?= htmlspecialchars($userSession->getFullName()); ?></a></strong>
                        
                    </div>
                    <?php
                    if ($userSession->getAdmin() ==1) {
                    ?>
                    <a href="<?= $requestUrl ?>/admin">Interface admin</a>
                    <?php
                    }
                    ?>
                    <a href="<?= $requestUrl ?>/user/logout">Déconnexion</a>
				<?php
                }
                else {
                ?>
                <a href="<?= $requestUrl ?>/user">Créer un compte</a>
				<a href="<?= $requestUrl ?>/user/login">S'identifier</a>
                <?php
                }
                ?>
		</section>
		<header>
			<a id="guigs-logo" href="<?= $requestUrl ?>"><img class="logo" src="<?= $wwwUrl ?>/images/guigs-logo.png"></img></a>
			<nav>
				<a href="<?= $requestUrl ?>/artists">Artistes</a>
				<a href="<?= $requestUrl ?>/records">Albums</a>
				<?php
				if($userSession->isAuthenticated()) {
			    ?>
				<a href="<?= $requestUrl ?>/wantlist">Ma Wantlist</a>
				<?php
				}
				?>
				<a href="<?= $requestUrl ?>">About Guigscog</a>
			</nav>
		</header>
    
    <main>
        <!-- Affichage du template lié à la vue -->
        <?php include $this->viewData['template'] ?>
    </main>
    
    <!-- Pied de page commun -->
    <footer>
        <a href="<?= $requestUrl ?>">Accueil</a>
        <a href="">About Guigscog</a>
        <a href="<?= $requestUrl ?>/contact">Nous contacter</a>
    </footer>
    
    <!-- Code principal JavaScript de l'application -->
    <script src="<?= $wwwUrl ?>/js/main.js"></script>
    
    </body>
</html>