<!-- S'il y des message de notifications de types flashBags, on les affiche dans un aside #notice -->
<?php if($flashBag->hasMessages() == true): ?>
    <aside id="notice" class="notice">
        <?php foreach($flashBag->fetchMessages() as $message): ?>
            <p><?= $message ?></p>
        <?php endforeach ?>
    </aside>
<?php endif; ?>

<!-- Affichage du template lié à la vue -->
<h2><i class="fa fa-lock"></i> Se connecter avec un compte utilisateur</h2>

<form class="generic-form" action="<?= $requestUrl; ?>/user/login" method="POST">
    
    <!-- aside qui s'affichera en cas d'erreur dans le formulaire -->
    <aside class="error-message hidden">
		<h3><i class="fa fa-warning"></i> Il y a <em class="validation-error-count">1</em> erreur(s) dans le formulaire !</h3>
		<p></p>
	</aside>
	
	<ul>
		<li>
			<label for="email">E-mail</label>
			<input id="email" type="text" name="email" data-required data-name="E-mail" value="<?= $email;?>">
		</li>
		<li>
			<label for="password">Mot de passe</label>
			<input id="password" type="password" name="password" data-required data-name="Mot de passe">
		</li>
	</ul>

	<ul>
		<li>
			<input class="button" type="submit" value="Connexion">
			<a class="button" href="<?= $requestUrl; ?>">Annuler</a>
		</li>
	</ul>
	
</form>